#' Decode fragment array to data.table
#'
#' @param fragmentArray a fragment array generated by fragments2tensor or a
#'   model.
#'
#' @return
#' @export
#' 

decodeFragArray <- function(fragmentArray){
  #Break each row into data.table
  dtList <- apply(X = fragmentArray, MARGIN = 1, FUN = as.data.table)
  #add row index
  dtList <- lapply(X = dtList, FUN = function(X){X[,rowIndex := c(1:nrow(X))]})
  
  #combine, melt, label
  dtList <- rbindlist(dtList, idcol = TRUE)
  dtList <- melt(data = dtList, id.vars = c(".id", "rowIndex"))
  setnames(x = dtList, old = c(".id", "rowIndex", "variable", "value"), new = c("sequence", "fragmentLength", "type_charge", "intensity"))
  
  #add info
  splits <- strsplit(x = as.character(dtList$type_charge), split = "_")
  dtList[, fragment_type := sapply(splits, "[[", 1)]
  dtList[, fragment_charge := sapply(splits, "[[", 2)]
  dtList[, fragment_type := paste0(fragment_type, fragmentLength)]
  
  splits <- strsplit(x = dtList$sequence, split = "_")
  dtList[, sequence := sapply(splits, "[[", 1)]
  dtList[, precursorCharge := sapply(splits, "[[", 2)]
  
  dtList
}

#' Compare results from model to known answer
#'
#' @param model a trained model with method in predict()
#' @param test_x input sequence array to generate predicted fragment pattern
#' @param test_y known answer encoded as an array 
#'
#' @return a data.table
#' @export
#'

compareFragResults <- function(model, test_x, test_y){
  model_result <- predict(object = model, test_x)
  dimnames(model_result) <- dimnames(test_y)
  
  #Convert arrays to actual ions
  model_result <- decodeFragArray(model_result)
  model_result$intensity <- model_result$intensity * -1
  model_result[,isModel := TRUE]
  
  answer <- decodeFragArray(test_y)
  answer[,isModel := FALSE]
  
  answer <- rbindlist(list(model_result, answer))
  
  
  #answer[, peptideIndex := match(x = sequence, table = unique(sequence))]
  answer
}

#' Visualize comparison of model to known
#'
#' @param compareResultsDt data.table returned by compareFragResults
#'
#' @return
#' @export
#'

compareFragResults_plot <- function(compareResultsDt){
  ggplot(data = compareResultsDt, aes(x = fragment_type , y = intensity, fill = fragment_charge))+
    geom_bar(stat = "identity", position = "dodge")+
    facet_wrap("sequence", scales = "free")+
    geom_hline(yintercept = 0)+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
}




correlateFragResults <- function(model, test_x, test_y){
  model_result <- predict(object = model, test_x)
  dimnames(model_result) <- dimnames(test_y)
  
  #Convert arrays to actual ions
  model_result <- decodeFragArray(model_result)
  answer <- decodeFragArray(test_y)
  
  answer <- merge(x = answer, y = model_result, by = c("sequence", "fragmentLength", "type_charge", "fragment_type", "fragment_charge", "precursorCharge"))
  
  answer
}